### ISSUE TITLE
Your demo website is broken

### ISSUE THREAD

**Issue by sylwesterdigital** [qinshenxue/vue-icon#30]
Hi there. I was looking for relevant icons for my VR/WebXR section of the website,
and noticed that your website is no more working properly

https://qinshenxue.github.io/vue-icon/

``
Failed to load resource: the server responded with a status of 404 ()
(index):1539 Uncaught ReferenceError: Vue is not defined
    at (index):1539:5
``

**Comment by qinshenxue** [comment]
@sylwesterdigital 
now is available
